SOURCES = ringbuffer.mli ringbuffer.ml IO.ml audio_c.c oss_io_c.c audio.mli	\
audio.ml image_c.h image_c.c image.mli image.ml video.mli video.ml MIDI.mli MIDI.ml	\
synth.mli synth.ml
RESULT = mm
OCAMLFLAGS = -g
OCAMLNCFLAGS = -p

all: ncl

include OCamlMakefile
